### ISSUE TITLE
Dependancy Error

### ISSUE THREAD

**Issue by uynil** [mcous/svgerber#31]
I got the dependacy error, after installing all the things.

```
root@iZ94hmaqa7oZ:/home/deploy/svgerber# gulp 
module.js:339
    throw err;
    ^

Error: Cannot find module 'ansi-regex'
    at Function.Module._resolveFilename (module.js:337:15)
    at Function.Module._load (module.js:287:25)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Object.<anonymous> (/home/deploy/svgerber/node_modules/gulp-util/node_modules/chalk/node_modules/strip-ansi/index.js:2:17)
    at Module._compile (module.js:435:26)
    at Object.Module._extensions..js (module.js:442:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Module.require (module.js:366:17)
```

**Comment by mcous** [comment]
I am unable to reproduce with Node.js v4.2.1 and npm v3.3.10. It seems like an `npm install` error. You could try deleting `node_modules` and running `npm install` again. If it still doesn't work, I'd suggest deleting `node_modules

**Comment by uynil** [comment]
Thanks for the fast feedback.
I have solved this issue by upgrading npm version (from 2.4 to 3.3 ) and
reinstall dependencies.
